name: "Slack Message"
description: "Send a message to Slack with optional thread reply"
inputs:
  channel_id:
    description: "Slack channel ID"
    required: true
  message:
    description: "Main message to send"
    required: false
  message_ts:
    description: "Timestamp of existing message to reply to in thread (if provided, main message will be skipped)"
    required: false
  thread_message:
    description: "Optional thread reply message"
    required: false
  token:
    description: "Slack OAuth token"
    required: true

outputs:
  message_ts:
    description: "Timestamp of the main message"
    value: ${{ steps.main_message.outputs.ts || inputs.message_ts }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail

        if [ -z "${{ inputs.message }}" ] && [ -z "${{ inputs.message_ts }}" ]; then
          echo "ERROR: Either 'message' or 'message_ts' must be provided"
          exit 1
        fi

        if [ -n "${{ inputs.message_ts }}" ] && [ -z "${{ inputs.thread_message }}" ]; then
          echo "ERROR: When 'message_ts' is provided, 'thread_message' is required"
          exit 1
        fi

        # If message_ts is provided, verify the parent message exists in Slack
        if [ -n "${{ inputs.message_ts }}" ] && [ -z "${{ inputs.message }}" ]; then
          echo "Verifying message with timestamp ${{ inputs.message_ts }} exists in Slack"

          RESPONSE=$(curl -s -X GET "https://slack.com/api/conversations.history" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -d "channel=${{ inputs.channel_id }}" \
            -d "latest=${{ inputs.message_ts }}" \
            -d "limit=1" \
            -d "inclusive=true")

          if ! echo "$RESPONSE" | jq -e '.ok' > /dev/null; then
            SLACK_ERROR=$(echo "$RESPONSE" | jq -r '.error // "unknown error"')
            echo "ERROR: Failed to verify message existence: $SLACK_ERROR. Is your channel_id correct?"
            exit 1
          fi

          MESSAGE_COUNT=$(echo "$RESPONSE" | jq '.messages | length')
          if [ "$MESSAGE_COUNT" -eq 0 ]; then
            echo "ERROR: No messages found since timestamp ${{ inputs.message_ts }} in channel ${{ inputs.channel_id }}.  Is your channel_id correct?"
            exit 1
          fi

          MESSAGE_TS=$(echo "$RESPONSE" | jq -r '.messages[0].ts')
          if [ "$MESSAGE_TS" != "${{ inputs.message_ts }}" ]; then
            echo "ERROR: Message timestamp mismatch. Expected ${{ inputs.message_ts }}, got $MESSAGE_TS.  Is your channel_id correct?"
            exit 1
          fi

          echo "Found parent message."
        fi
    - name: Send main message to Slack channel
      if: ${{ inputs.message_ts == '' && inputs.message != '' }}
      uses: slackapi/slack-github-action@v2
      id: main_message
      with:
        errors: true
        method: chat.postMessage
        token: ${{ inputs.token }}
        payload: |
          channel: "${{ inputs.channel_id }}"
          text: "${{ inputs.message }}"
    - name: Send thread reply
      if: ${{ inputs.thread_message != '' }}
      uses: slackapi/slack-github-action@v2
      id: thread_reply
      with:
        method: chat.postMessage
        token: ${{ inputs.token }}
        payload: |
          channel: "${{ inputs.channel_id }}"
          thread_ts: "${{ inputs.message_ts || steps.main_message.outputs.ts }}"
          text: "${{ inputs.thread_message }}"
