name: "Slack User Lookup"
description: "Look up Slack user IDs based on GitHub usernames using a pre-built mapping"
inputs:
  github_usernames:
    description: "Space-delimited string of GitHub usernames to look up"
    required: true
  github_slack_mapping:
    description: "JSON string of an object mapping GitHub usernames to Slack user IDs"
    required: true

outputs:
  slack_users:
    description: "JSON array of Slack user IDs that were matched"
    value: ${{ steps.build-mentions.outputs.slack-users }}
  github_users:
    description: "JSON array of GitHub usernames that couldn't be matched to Slack users"
    value: ${{ steps.build-mentions.outputs.github-users }}
  formatted_string:
    description: "Comma-separated string of formatted mentions (Slack users as <@ID>, unmatched GitHub users as @username)"
    value: ${{ steps.build-mentions.outputs.formatted-string }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      id: validate
      shell: bash
      run: |
        echo "slack-users=[]" >> $GITHUB_OUTPUT
        echo "github-users=[]" >> $GITHUB_OUTPUT
        echo "formatted-string=" >> $GITHUB_OUTPUT

        if ! echo '${{ inputs.github_slack_mapping }}' | jq empty 2>/dev/null; then
          echo "Error: github_slack_mapping is not valid JSON"
          exit 1
        fi

        if [ "$(echo '${{ inputs.github_slack_mapping }}' | jq -r 'type')" != "object" ]; then
          echo "Error: github_slack_mapping must be a JSON object"
          exit 1
        fi

        if [ -z '${{ inputs.github_usernames }}' ]; then
          echo "Error: no github_usernames were provided."
          exit 1
        fi

    - name: Build mentions and find unmatched
      id: build-mentions
      shell: bash
      run: |
        GITHUB_USERNAMES='${{ inputs.github_usernames }}'
        GITHUB_SLACK_MAP='${{ inputs.github_slack_mapping }}'

        IFS=' ' read -ra USERNAME_ARRAY <<< "$GITHUB_USERNAMES"

        SLACK_USERS="[]"
        GITHUB_USERS="[]"

        for github_username in "${USERNAME_ARRAY[@]}"; do
          if [ -n "$github_username" ]; then
            SLACK_USER_ID=$(echo "$GITHUB_SLACK_MAP" | jq -r --arg github_user "$github_username" '.[$github_user] // ""')
            
            if [ -n "$SLACK_USER_ID" ] && [ "$SLACK_USER_ID" != "null" ] && [ "$SLACK_USER_ID" != "" ]; then
              SLACK_USERS=$(echo "$SLACK_USERS" | jq --arg user_id "$SLACK_USER_ID" '. + [$user_id]')
            else
              GITHUB_USERS=$(echo "$GITHUB_USERS" | jq --arg username "$github_username" '. + [$username]')
            fi
          fi
        done

        # Build formatted string with mentions
        FORMATTED_STRING=$(echo "$SLACK_USERS $GITHUB_USERS" | jq -r -s '
          (.[0] | map("<@" + . + ">")) + (.[1] | map("@" + .)) | join(", ")
        ')

        echo "slack-users=$(echo "$SLACK_USERS" | jq -c .)" >> $GITHUB_OUTPUT
        echo "github-users=$(echo "$GITHUB_USERS" | jq -c .)" >> $GITHUB_OUTPUT
        echo "formatted-string=$FORMATTED_STRING" >> $GITHUB_OUTPUT
