name: "Pickaroo Reviewers"
description: "Selects a number of random reviewers from included and excluded teams"
inputs:
  include_teams:
    description: The github teams to pick reviewers from (space delimited)
    required: false
  exclude_teams:
    description: The github teams to exclude reviewers from (space delimited)
    required: false
  include_users:
    description: Individual GitHub usernames to include (space delimited)
    required: false
  exclude_users:
    description: Individual GitHub usernames to exclude (space delimited)
    required: false
  number_of_reviewers:
    default: "1"
    description: The number of reviewers to select
  github_slack_mapping:
    description: "JSON string of an object mapping GitHub usernames to Slack user IDs. Used to filter reviewers by slack status"
    required: false
  slack_token:
    description: "Required if you provide a value to github_slack_mapping"
    required: false
  token:
    description: a github token with permissions to read org teams and modify pull requests
    required: true

outputs:
  reviewers:
    description: "Space-delimited string of selected reviewer usernames"
    value: ${{ steps.select-reviewers.outputs.reviewers }}

runs:
  using: "composite"
  steps:
    - name: Select reviewers
      id: select-reviewers
      shell: bash
      run: |
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"

        # Get members from all include teams
        TEAM_MEMBERS="[]"
        if [ -n "${{ inputs.include_teams }}" ]; then
          for team in ${{ inputs.include_teams }}; do
            MEMBERS=$(gh api orgs/newjersey/teams/$team/members --jq 'map(.login)')
            TEAM_MEMBERS=$(echo "$TEAM_MEMBERS $MEMBERS" | jq -s 'add | unique')
          done
        fi
        echo "included teams $TEAM_MEMBERS"

        # Add individual include users
        INCLUDE_USERS="[]"
        if [ -n "${{ inputs.include_users }}" ]; then
          INCLUDE_USERS=$(echo "${{ inputs.include_users }}" | tr ' ' '\n' | jq -R -s 'split("\n") | map(select(length > 0))')
        fi
        echo "included users $INCLUDE_USERS"

        # Combine team members and individual users
        ALL_INCLUDED=$(echo "$TEAM_MEMBERS $INCLUDE_USERS" | jq -s 'add | unique')
        echo "all included $ALL_INCLUDED"

        # Get members from all exclude teams
        EXCLUDE_MEMBERS="[]"
        if [ -n "${{ inputs.exclude_teams }}" ]; then
          for team in ${{ inputs.exclude_teams }}; do
            MEMBERS=$(gh api orgs/newjersey/teams/$team/members --jq 'map(.login)')
            EXCLUDE_MEMBERS=$(echo "$EXCLUDE_MEMBERS $MEMBERS" | jq -s 'add | unique')
          done
        fi

        # Add individual exclude users
        EXCLUDE_USERS="[]"
        if [ -n "${{ inputs.exclude_users }}" ]; then
          EXCLUDE_USERS=$(echo "${{ inputs.exclude_users }}" | tr ' ' '\n' | jq -R -s 'split("\n") | map(select(length > 0))')
        fi

        # Combine excluded team members and individual users
        ALL_EXCLUDED=$(echo "$EXCLUDE_MEMBERS $EXCLUDE_USERS" | jq -s 'add | unique')
        echo "all excluded $ALL_EXCLUDED"

        EXISTING_REVIEWERS=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers --jq '.users | map(.login)')
        echo "existing reviewers $EXISTING_REVIEWERS"

        COLLABORATORS=$(gh api repos/${{ github.repository }}/collaborators --jq 'map(.login)')

        FILTERED_MEMBERS=$(echo $ALL_INCLUDED | jq -r --arg author "$PR_AUTHOR"\
          --argjson exclude "$ALL_EXCLUDED"\
          --argjson existing "$EXISTING_REVIEWERS"\
          --argjson collaborators "$COLLABORATORS" 'map(select(. != $author and (. as $member | $exclude | index($member) | not) and (. as $member | $existing | index($member) | not) and (. as $member | $collaborators | index($member)))) | unique | .[]')

        # Filter out users based on Slack status if mapping is provided
        if [ -n "${{ inputs.github_slack_mapping }}" ] && [ -n "${{ inputs.slack_token }}" ]; then
          echo "Filtering based on Slack status..."
          SLACK_FILTERED_MEMBERS=""
          
          for member in $FILTERED_MEMBERS; do
            SLACK_USER_ID=$(echo '${{ inputs.github_slack_mapping }}' | jq -r --arg github_user "$member" '.[$github_user] // empty')
            
            if [ -n "$SLACK_USER_ID" ] && [ "$SLACK_USER_ID" != "null" ]; then
              # Get user's Slack profile
              PROFILE_RESPONSE=$(curl -s -X GET "https://slack.com/api/users.profile.get?user=$SLACK_USER_ID" \
                -H "Authorization: Bearer ${{ inputs.slack_token }}")
              
              STATUS_TEXT=$(echo "$PROFILE_RESPONSE" | jq -r '.profile.status_text // ""')
              STATUS_EMOJI=$(echo "$PROFILE_RESPONSE" | jq -r '.profile.status_emoji // ""')
              
              # Check if status indicates unavailability (case insensitive)
              STATUS_LOWER=$(echo "$STATUS_TEXT $STATUS_EMOJI" | tr '[:upper:]' '[:lower:]')
              
              if echo "$STATUS_LOWER" | grep -qE "(out of office|ooo|sick|flu|vacation|unavailable|leave|travel|thermometer|mask|vomiting|palm_tree)"; then
                echo "Filtering out $member due to Slack status: $STATUS_TEXT $STATUS_EMOJI"
              else
                SLACK_FILTERED_MEMBERS="$SLACK_FILTERED_MEMBERS$member\n"
              fi
            else
              # If no Slack mapping found, include the user
              SLACK_FILTERED_MEMBERS="$SLACK_FILTERED_MEMBERS$member\n"
            fi
          done
          
          FILTERED_MEMBERS=$(echo -e "$SLACK_FILTERED_MEMBERS" | grep -v '^$')
        fi

        RANDOM_ASSIGNEES=$(echo "$FILTERED_MEMBERS" | shuf -n ${{ inputs.number_of_reviewers }} )
        echo "Selected reviewers: $RANDOM_ASSIGNEES"

        if [ -n "$RANDOM_ASSIGNEES" ]; then
          REVIEWERS_JSON=$(echo "$RANDOM_ASSIGNEES" | jq -R -s 'split("\n") | map(select(length > 0))')
          
          # Set output as space-delimited string
          REVIEWERS_STRING=$(echo "$RANDOM_ASSIGNEES" | tr '\n' ' ' | sed 's/[[:space:]]*$//')
          echo "reviewers=$REVIEWERS_STRING" >> $GITHUB_OUTPUT
          
          curl -L -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d "{\"reviewers\":$REVIEWERS_JSON}"
        else
          echo "reviewers=" >> $GITHUB_OUTPUT
          echo "No available members to request review from based on filters"
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
