name: npm audit

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use (e.g., '20') or a file path (e.g., '.nvmrc')"
        required: false
        default: ".nvmrc"
        type: string
      audit-level:
        description: "npm audit severity threshold"
        required: false
        default: "critical"
        type: string

permissions:
  contents: read

jobs:
  npm-audit:
    name: Critical vulnerabilities
    runs-on: ubuntu-latest
    outputs:
      audit_status: ${{ steps.audit-status.outputs.audit_status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run npm audit
        id: audit-status
        uses: ./.github/actions/npm-audit
        with:
          node-version: ${{ inputs.node-version }}
          audit-level: ${{ inputs.audit-level }}
