name: "Pull Request Review"

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  request-project-reviewers:
    if: ${{ github.event.label.name == 'pr-review' }}
    uses: ./.github/workflows/pickaroo.yml
    secrets: inherit
    with:
      include_users: "timwright12 jviall aloverso"
      channel_id: C03C7NHK9B4 # engineering-all
      extras: false # 1 of these is always enough
      slack_as_author: true
  request-initiative-reviewers:
    if: ${{ github.event.label.name == 'pr-review' }}
    needs: request-project-reviewers # avoid a race between jobs
    uses: ./.github/workflows/pickaroo.yml
    secrets: inherit
    with:
      include_teams: "innovation-engineering"
      exclude_users: "dhcole timwright12 jviall aloverso"
      channel_id: C03C7NHK9B4 # engineering-all
      slack_as_author: true
  pr-show:
    if: ${{ github.event.label.name == 'pr-show' }}
    uses: ./.github/workflows/pickaroo.yml
    secrets: inherit
    with:
      show: true
      channel_id: C03C7NHK9B4 # engineering-all
      slack_as_author: true
  test-pr-review:
    if: ${{ github.event.label.name == 'test-pr-review' }}
    uses: ./.github/workflows/pickaroo.yml
    secrets: inherit
    with:
      include_teams: "innovation-engineering"
      channel_id: C09Q36G9HMX # sandbox
      slack_as_author: true
  test-pr-show:
    if: ${{ github.event.label.name == 'test-pr-show' }}
    uses: ./.github/workflows/pickaroo.yml
    secrets: inherit
    with:
      show: true
      channel_id: C09Q36G9HMX # sandbox
      slack_as_author: true
